### ISSUE TITLE
[meta] How to use the repo?

### ISSUE THREAD

**Issue by oxyc** [oxyc/travels#16]
- [x] Commit country maps thourgh geojson.io
- [x] Embed highlights as Instagram photos
- [x] Embed photo album from picasa
- [x] Fields for expenditures
- [x] Fields for visits
- [ ] Would be nice to have get a feed of all instagram/fb photos related to a country
- [x] Map filterable by trips
- [x] Trips should include routes
- [x] Route distance

**Comment by oxyc** [comment]
- [x] Commit country maps thourgh geojson.io
- [x] Embed highlights as Instagram photos
- [ ] Embed photo album from picasa
- [x] Fields for expenditures
- [x] Fields for visits
- [ ] Would be nice to have get a feed of all instagram/fb photos related to a country
- [ ] Map filterable by trips
